# Literature Review

## *Cross-Sectional Predictability of Stock Returns in the UK*

We begin this study by exploring the effectiveness of different predictors in equity asset pricing.
The Capital Asset Pricing Model developed by @RN62, @RN63, and @RN64 gives an intuitive and fundamental explanation in terms of the relation between asset returns and market performance with the following equation:

\begin{equation}
\tag{1}
E\left[R_i\right]-E\left[R_f\right]=\beta_{i,M}\left(E\left[R_M\right]-E\left[R_f\right]\right)
\end{equation}

However, the empirical study of US stocks by @RN72 confirms that the CAPM failed to explain the alpha calculated from the model as the intercept is way higher than the risk-free rate. They also imply the beta of the model could not capture the whole picture of the movement of stock returns and the actual relation between beta and return is flatter than that estimated by the CAPM. Twenty years later, @RN67 further confirm in the cross-section of US stock returns, beta is empirically not priced. This result is validated by the low-beta or low-volatility effects shown in some recent studies such as @RN76 and @RN77. @RN78 raises a famous critique that the CAPM requires a mean-variance effective market portfolio that is not observable and thus economists can only approximate the market with proxies such as a market index. 

We call these parts of stock returns that can’t be explained by the CAPM anomalies. One of the most popular models trying to address the anomalies is the @RN66 three-factor model, in which they demonstrate the explanatory power of size and book-to-market equity in the cross-section of average stock returns. The @RN66 three-factor model can be boiled down to the following equation:

\begin{equation}
\tag{2}
R_{i,t}=\alpha_i+\beta_{i,1}\left(R_M-R_{f,t}\right)+\beta_{i,2}SMB_t+\beta_{i,3}HML_t+\varepsilon_{i,t}
\end{equation}

In the equation above, $R_{i,t}$, is the return of portfolio or asset $i$ in the month $t$, $R_M-R_{f,t}$ is the market excess return, $\varepsilon_{i,t}$ is the residual error, $\alpha_i$ is the intercept item, $\beta_{i,1}$,$\beta_{i,2}$, and $\beta_{i,3}$ measure the risk exposure to each of the three factors. After the birth of the three-factor model, it has become to some extent an industry standard to use the model and its approach to evaluate performance in asset pricing. @RN66 use an independent double sort method to construct the factor portfolios and then calculate the value-weighted return of each portfolio. They sort stocks in 2 size groups and 3 book-to-market groups and hence 6 portfolios. With these sorted data, the return of SMB factor (Small minus Big) and HML factor (High minus Low) in every single month can be extracted by calculating the difference between the return of stocks with small and big market sizes and the difference between the return of stocks with high and low book-to-market values. Results in @RN80 show that the three-factor model significantly outperforms the CAPM in explaining the cross-sectional returns of stocks in the US market and most of the anomalies except short-term momentum can be modeled by these three factors.

@RN17 update the three-factor model by introducing two new variables – profitability factor or RMW (Robust minus Weak) and investment factor or CMA (Conservative minus Aggressive) – partially motivated by a series of new factors proposed in the literature of asset pricing models. For example, @RN73 propose a cross-sectional momentum premium and document that a strategy that longs winner stocks and shorts loser stocks over the last 3-12 months realizes significant extra returns. Similarly, @RN81 expands the three-factor model to a four-factor model by including a 12-month MoM factor (momentum) or WML factor (winners minus loser) as called in some literature. He uses the same way to construct the WML portfolio as @RN66 to HML. @RN23 finds controlling profitability can increase the performance of value portfolios and therefore proposes a gross profitability premium to explain this new anomaly. @RN82 documents an accrual anomaly that is due to the irrationality of investors. He suggests that an investment strategy that goes long on low accruals firms and short on high accruals firms yields an annual abnormal return of 10.4%. @RN83 pointed out that net external financing is a negative indicator of future stock returns. The net external financing factor defined as an aggregate of corporate financing activities such as equity issuances, equity repurchases, debt issuances, etc., according to @RN83, can yield an annual portfolio return of 15.5%. @RN75 find total asset growth rate is a strong and dominant predictor of cross-sectional future returns and document a value-weighted return spread of 8.4% per year between firms with low asset growth rates and firms with high asset growth rates. @RN84 report the net operating assets factor, which is defined as the difference between cumulative earnings and cumulative free cash flow over time, is an indicator of the overoptimism of investors over the “bloated” accounting outcomes and therefore negatively predicts future returns. Some other research suggests that measures such as size-matched sales and leverage ratio also contain information about future returns (for example, @RN68 employ the Fama-French approach to explain the cross-section of UK stock returns and find leverage ratio along with book-to-market equity has a consistent explanatory power for the UK expected stock returns over 1973-1992).

Although the five-factor model of @RN17 significantly increases the explanatory power by capturing from 71% to 94% of the cross-section variations of expected returns compared to their initial three-factor model, it has left some problems unanswered.[^1] For example, the HML variable seems to become redundant because the large average HML return is absorbed by the exposures of HML to the other four factors, especially the profitability and investment factors. Another problem of the Fama-French five-factor model, as pointed out by themselves, is “its failure to capture the low average returns on small stocks whose returns behave like those of firms that invest a lot despite low profitability”. @RN19 show empirical evidence that the Fama-French five-factor model may not be optimal for emerging markets in terms of factor definitions. Most important, one prominent anomaly is still missing, namely the momentum anomaly. @RN71 argued that a timelier HML (i.e., updated monthly with the latest market capitalization) together with a momentum factor creates a more robust model than the Fama-French five-factor model, thanks to the diversification benefits of value and its negative correlation with the momentum factor. @RN65 confirms this result by showing that the six-factor model with a monthly updated value factor, a momentum factor, and a cash-based profitability factor outperforms the other six prominent models.

Momentum is categorized as a “persistence” factor and hence tends to benefit from continued trends in markets. In the following analysis, our test results have confirmed that momentum contributes more than the other factors to explaining expected returns in UK stock markets. One of our main revisions to the Fama-French five-factor model is that we incorporate a system of momentum factors, i.e., seasonal MoM, 6-month MoM, and 12-month MoM, in our tests and model building. Jegadeesh and Lakonishok (1996) explain the momentum anomaly as a market inefficiency, which is caused by a slow reaction to information. However, according to @RN86, the effect of the momentum factors diminishes if stretched beyond 12 months. @RN81 shows that the momentum factor outperforms the standard @RN66 three factors, namely excess market factor, size factor, and value factor. @RN87 consider the behavioral patterns of investors and thus introduce a seasonal momentum factor that measures seasonal predictability in the cross-section of stock returns. They confirm that the short-term momentum anomaly exists in Canada and Europe, but is not effective in Japan. They also find that in all cases longer-term momentum strategies are less profitable than short-term momentum strategies. Seasonal momentum tends to capture effects such as the widely documented January anomaly (i.e., the outperformance of smaller stocks in January, which can be explained by investors reentering the market after selling their stocks at year-end for tax purposes). 

In this paper, we follow a process similar to that in @RN65. We first examine the performances of a set of factors from different categories in the @RN72 cross-sectional regressions. Then, we test the predictive power of expected returns based on the cross-sectional performances of factors in the same way as in @RN46.

Here below is a summary of the out-of-sample predictive power test that is implemented in @RN46. @RN46 first defines 15 characteristics which are as he calls either level variables or flow variables, namely size, B/M, past 12-month stock returns, three-year share issuance, one-year accruals, profitability, asset growth, beta, dividend yield, one-year share issuance, three-year stock returns, 12-month volatility, 12-month turnover, market leverage, and the sales-to-price ratio. From these 15 characteristics, @RN46 derives 3 models based on the number of variables included. To align the accounting data with market data, a four-month lag was applied. That means accounting data are assumed to be observable by the end of April of year $t$ for fiscal year $t-1$. Subsequently, @RN46 conducts the Fama-MacBeth cross-sectional regressions as the basis of the out-of-sample test in the predictive powers of the three models. Essentially, the results of the regressions show that slopes on B/M, past 12-month returns (MoM), and profitability are significantly positive while the slopes on size, share issuance, accruals, and asset growth are significantly negative. As for the remaining variables, dividend yield, long-term returns, 12-month share issuance, and market leverage show no significant effect for the chosen sample. Turnover and the sales-to-price ratio are significant in the full-sample data with a -4.49 and 0.04 slope respectively. The effect of a firm’s beta of the prior year is significantly positive over the return of the next year while the effect of volatility is significantly negative for some of the sample groups. 

The next step of @RN46 is to simulate what an investor would have forecast for expected returns using information from prior Fama-MacBeth regressions such as a 10-year rolling average of intercepts and slopes and a firm’s beginning-of-month characteristics. The results of the forecast return distribution starting from 1964 reflect that adding more variables to the model slightly increases the dispersion of the forecasts. It also shows that for example in the full-sample group, the predictive powers (i.e., the slope of subsequent realized returns over forecasts of returns) range from 0.74 to 0.80 depending on the number of predictors when applying a 10-year rolling window. In this forecast test, @RN46 finds in all three models and three sample groups, the predictive abilities represented by the slope are statistically significant with a minimum t-statistic of 2.08. The empirical result can be useful because it demonstrates that Fama-MacBeth-based expected-return estimates have strong predictive power for subsequent stock returns and buying those stocks estimated to perform better can effectively achieve a higher return in the future. That lays the cornerstone of our investment strategy as Fama-MacBeth regression provides a reliable way to forecast future returns.

@RN46 also carries out other forecast tests based on alternative rolling windows and finds that even using a rolling window as short as 12 months to get the Fama-MacBeth slopes, the predictive power is still relatively strong with nearly two-thirds of the slopes above 0.50. Furthermore, @RN46 points out that an equal-weighted or value-weighted High-minus-Low trading strategy based on the Fama-MacBeth expected return could be profitable. For example, a fund manager can achieve a Fama-French three-factor alpha of 0.53% for value-weighted portfolios of large stocks. @RN46 also proves that the predictive power of the Fama-MacBeth slopes in cross-sectional regressions still exists for at least one year by testing the forecasts of longer-horizon returns.

## *Asset allocation methods*

As classified in  @RN88, the currently practiced asset allocation models can be categorized into two classes: heuristic-based weighting and optimization-based weighting models. The heuristic-based weighting models are relatively simple asset allocation approaches mainly referring to the naïve equal-weighted approach or 1/N portfolio and the value-weighted approach. The optimization-based weighting models mainly consist of minimum-variance or minimum-volatility optimization, maximal Sharpe ratio optimization, and others such as Bayesian-estimation-based methods.

The naïve equal-weighted approach is a strategy that allocates a 1/N equal weight to every asset in the portfolio. The value-weighted allocation approach, as its name implies, allocates a portion to every asset according to its market capitalization. The turnover of a value-weighted portfolio is zero. Most market indices such as S&P 500 Index and Russell 1000 Index are value-weighted. Except for the two aforementioned simple-rule-based approaches, there are also several other choices for portfolio managers in this category. For example, @RN88 test the “Risk-Clusters Equal-Weighting” approach which equally allocates funds over quantitatively defined risk clusters and the “Diversity-Weighting” approach which is set to blend equal-weighted portfolios and value-weighted portfolios. @RN89 also report a fundamental weighting approach that weights stocks by their accounting data such as sales and book value because they think market pricing error could lead to suboptimal allocations. Research also reports other risk-balanced weighting methods such as the risk parity approach by @RN91 which weights stocks counter-proportionally to their variances.

Minimum-variance optimization utilizes the low-volatility anomaly which indicates stocks with lower volatility often have a higher return-to-risk ratio. It aims to minimize the volatility of the portfolio and implicitly assumes that the expected returns of all stocks are all the same. The objective function of the optimization problem can be written as:

\begin{equation}
\tag{3}
\min\limits_{\omega}{\omega^\prime\Sigma\omega}
\end{equation}

where $\omega$ is the vector of weights and $\Sigma$ is the estimated covariance matrix of expected returns. @RN88 show that the minimum-variance strategy achieves a top Sharpe ratio among all seven tested strategies (2/7 in global developed portfolios and 1/7 in U.S. portfolios) although it also reports the highest tracking error in both markets. 

Maximal Sharpe ratio optimization is a further improvement on the minimum-variance optimization. It aims at calculating the weights that maximize the ex ante Sharpe ratio. @RN88 form two maximal Sharpe ratio portfolios with the return volatility $\sigma_i$ and downside semi-volatility $\widehat{\sigma_i}$ as a proxy for estimated return, respectively. They reported strong Sharpe ratios for both strategies and high annual excess returns over the benchmark (2.52% and 3.00% for U.S. portfolios, respectively). On the other hand, higher one-way turnover rates (56.02% and 34.19% respectively) are not surprising. They enforced no short-selling and a concentration of weight limited to 10% in the concentration. They also follow @RN91 by using a similar shrinkage method in estimating volatilities and covariance matrix. @RN19 applied the maximal Sharpe ratio optimization to their emerging market factor model and report a good outperformance over all other investment strategy combinations with a Sharpe ratio of 0.95. @RN36 introduce a new method to implement maximal Sharpe ratio optimization. They applied the earnings-forecasts-based implied cost of capital (ICC) rather than the Fama-French-based expected return as an estimate of stock return in the maximum Sharpe ratio problem to reduce the estimation errors. To correct for analysts’ sluggishness with earnings forecasts, they add the rescaled momentum and subtract the risk-free rate to get the expected excess return. Their insightful results show that the maximum Sharpe ratio portfolio using the adjusted ICC measure largely outperforms the other tested optimization models such as the equally-weighted portfolio and the minimum-variance portfolio.

[^1]: @RN69 also raise some more concerns with the Fama-French five-factor model.
